baseURL = "http://example.org/"
languageCode = "en-us"
title = "MSF Makes"
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  projects = "/:filename/"
  about = "/:filename/"

[menu]
  [[menu.main]]
    name = "PROJECTS"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "MAKERS"
    url = "/makers/"
    weight = 2
  [[menu.main]]
    name = "ABOUT"
    url = "/about/"
    weight = 3